// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyOydhtNxZ-IH90TyVRti0SpTEzY-Lo4',
    appId: '1:984741663293:web:671b7b701b7879f2fcd054',
    messagingSenderId: '984741663293',
    projectId: 'smart-irrigation-app-c9fe3',
    authDomain: 'smart-irrigation-app-c9fe3.firebaseapp.com',
    storageBucket: 'smart-irrigation-app-c9fe3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgehBpAr0vI8VExyw_pPi-vv-IRdXHrQ',
    appId: '1:984741663293:android:433fb8ecdbb63518fcd054',
    messagingSenderId: '984741663293',
    projectId: 'smart-irrigation-app-c9fe3',
    storageBucket: 'smart-irrigation-app-c9fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkRSKxhO4-8C_P3jWB1AKwA3EI48pCAKo',
    appId: '1:984741663293:ios:297b1e161c98b231fcd054',
    messagingSenderId: '984741663293',
    projectId: 'smart-irrigation-app-c9fe3',
    storageBucket: 'smart-irrigation-app-c9fe3.appspot.com',
    iosBundleId: 'com.example.irrigationControlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkRSKxhO4-8C_P3jWB1AKwA3EI48pCAKo',
    appId: '1:984741663293:ios:2fd3df1ce58f4d7bfcd054',
    messagingSenderId: '984741663293',
    projectId: 'smart-irrigation-app-c9fe3',
    storageBucket: 'smart-irrigation-app-c9fe3.appspot.com',
    iosBundleId: 'com.example.irrigationControlApp.RunnerTests',
  );
}
